name: Run tests

on:
  push:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        uses: bahmutov/npm-install@v1.6.0

      - name: Run Cypress
        run: npm run test
